"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { SignalLabClaim, SignalLabEvidence, SignalLabView, LabOption, LabSurface } from "@/lib/design-lab/signal/types";
import { LAB_OPTIONS, LAB_SURFACES } from "@/lib/design-lab/signal/types";
import styles from "./signal-lab.module.css";

const optionNames: Record<LabOption, string> = { A: "Quiet Briefing Ledger", B: "Editorial Morning Brief", C: "Signal Lens" };
const surfaceNames: Record<LabSurface, string> = { briefing: "Briefing", today: "Today Signal", evidence: "Evidence", history: "Scope + history" };
const scenarioLabels: Record<string, string> = { normal: "Normal", quiet: "Quiet day", dense: "Dense input", edge: "Edge cases", stale: "Stale source", outage: "Partial outage", "first-day": "First day", empty: "No work" };
const selectOptions = {
  scenario: Object.entries(scenarioLabels), role: [["creator", "Creator"], ["collaborator", "Collaborator"], ["guest", "Guest"]], uiState: [["default", "Default"], ["loading", "Loading"], ["empty", "Empty"], ["error", "Error"], ["read-only", "Read-only"], ["feedback-submitted", "Feedback submitted"]], viewport: [["phone", "Phone"], ["tablet", "Tablet"], ["desktop", "Desktop"]], scopeKind: [["workspace", "Workspace"], ["planning-period", "Planning period"]],
};

function queryFromView(view: SignalLabView) { return new URLSearchParams({ option: view.query.option, surface: view.query.surface, scenario: view.query.scenario, role: view.query.role, uiState: view.query.uiState, viewport: view.query.viewport, scopeKind: view.query.scopeKind }); }

export default function SignalDesignLab({ initialView }: { initialView: SignalLabView }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const [view, setView] = useState(initialView); const [pending, startTransition] = useTransition(); const [status, setStatus] = useState("");
  const [evidence, setEvidence] = useState<SignalLabEvidence | null>(null); const [taskClaim, setTaskClaim] = useState<SignalLabClaim | null>(null); const [taskMessage, setTaskMessage] = useState("");
  const triggerRef = useRef<HTMLButtonElement | null>(null); const dialogRef = useRef<HTMLDialogElement | null>(null); const taskDialogRef = useRef<HTMLDialogElement | null>(null);
  const currentQuery = useMemo(() => new URLSearchParams(search.toString()), [search]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(currentQuery); next.set(key, value); startTransition(() => router.replace(`${pathname}?${next.toString()}`, { scroll: false })); setStatus(`${key} changed to ${value}`); };
  useEffect(() => { if (!pending) { const next = Object.fromEntries(currentQuery.entries()); void fetch(`/api/__design-lab/signal/view?${currentQuery.toString()}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : null).then((data) => data && setView(data)); } }, [currentQuery, pending]);
  useEffect(() => { if (evidence && dialogRef.current && !dialogRef.current.open) dialogRef.current.showModal(); }, [evidence]);
  useEffect(() => { if (taskClaim && taskDialogRef.current && !taskDialogRef.current.open) taskDialogRef.current.showModal(); }, [taskClaim]);
  const openEvidence = (claim: SignalLabClaim, button: HTMLButtonElement) => { triggerRef.current = button; fetch(`/api/__design-lab/signal/evidence/${claim.id}?${currentQuery.toString()}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : null).then((data) => { if (data) setEvidence(data); else setStatus("Evidence is not available to this role."); }); };
  const closeEvidence = () => { dialogRef.current?.close(); setEvidence(null); requestAnimationFrame(() => triggerRef.current?.focus()); };
  const closeTask = () => { taskDialogRef.current?.close(); setTaskClaim(null); requestAnimationFrame(() => triggerRef.current?.focus()); };
  const submitTask = () => { if (!taskClaim) return; fetch("/api/__design-lab/signal/task", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(currentQuery.entries()), claimId: taskClaim.id, confirmed: true }) }).then((r) => r.json()).then((result) => { setTaskMessage(result.status === "prepared" ? `Prepared ${result.taskId}. Nothing was written to Tasks.` : result.message ?? "Task handoff could not be prepared."); }); };
  const openTask = (claim: SignalLabClaim, button: HTMLButtonElement) => { triggerRef.current = button; setTaskClaim(claim); };
  const frameStyle = { "--x-lab-frame-width": view.query.viewport === "phone" ? "390px" : view.query.viewport === "tablet" ? "768px" : "100%" } as React.CSSProperties;

  return <div className={styles.root} data-option={view.query.option} data-surface={view.query.surface}>
    <a className={styles.skipLink} href="#main-content">Skip to lab surface</a>
    <header className={styles.reviewHeader}><div className={styles.reviewHeaderInner}><div className={styles.brandLockup}><span className={styles.brandName}>signal<span>·</span></span><span className={styles.reviewTitle}>Design lab</span></div><div className={styles.reviewMeta}><span className={styles.reviewOnly}>Review only</span><span>Fixture {view.datasetId}</span></div></div></header>
    <aside className={styles.inspector} aria-label="Design lab controls"><div className={styles.inspectorInner}>
      <fieldset className={styles.optionRow}><legend className={styles.optionLegend}>Direction</legend><div className={styles.optionSet}>{LAB_OPTIONS.map((option) => <button key={option} type="button" className={`${styles.optionButton} ${view.query.option === option ? styles.optionButtonActive : ""}`} aria-pressed={view.query.option === option} onClick={() => update("option", option)}><strong>{option}</strong><span>{optionNames[option]}</span></button>)}</div></fieldset>
      <nav className={styles.surfaceNav} aria-label="Lab surfaces">{LAB_SURFACES.map((surface) => <button key={surface} type="button" className={`${styles.surfaceLink} ${view.query.surface === surface ? styles.surfaceLinkActive : ""}`} aria-current={view.query.surface === surface ? "page" : undefined} onClick={() => update("surface", surface)}>{surfaceNames[surface]}</button>)}</nav>
      <details className={styles.reviewControls}><summary>Fixture controls <span aria-hidden="true">↗</span></summary><div className={styles.controlsGrid}>{Object.entries(selectOptions).map(([key, options]) => <label key={key} className={styles.control}><span className={styles.controlLabel}>{key === "scopeKind" ? "Scope" : key === "uiState" ? "UI state" : key[0].toUpperCase() + key.slice(1)}</span><select className={styles.select} value={(view.query as Record<string, string>)[key]} onChange={(event) => update(key, event.target.value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>)}</div></details>
      {pending && <p className={styles.pendingStatus} role="status">Updating preview…</p>}
    </div></aside>
    <main id="main-content" className={styles.stage} aria-busy={pending}>
      <div className={styles.viewportFrame} style={frameStyle}><div className={styles.productShell}><div className={styles.productTopbar}><div className={styles.productIdentity}><span className={styles.productDot} aria-hidden="true" />Signal</div><span>{view.scope.label}</span></div><div className={styles.scopeSummary}><span>{view.scope.kind === "workspace" ? "Workspace" : "Planning period"}</span><strong>{view.scope.label}</strong><span>{new Intl.DateTimeFormat("en-GB", { dateStyle: "full", timeZone: "Europe/London" }).format(new Date(view.generatedAt))}</span></div><div className={styles.trustStrip}><strong>{view.sourceStates.filter((s) => s.status === "fresh").length} sources current</strong><span>{view.coverageStatement}</span><span>{view.inputEventCount} inputs · {view.suppressedCandidateCount} held back</span></div>
        {view.mode === "loading" ? <Loading /> : view.mode === "error" ? <div className={styles.modeNotice} role="alert"><h1>{view.headline}</h1><p>{view.summary}</p></div> : view.query.surface === "history" ? <History view={view} /> : view.query.surface === "evidence" ? <EvidenceSurface view={view} onOpen={openEvidence} /> : view.query.surface === "today" ? <TodaySurface view={view} onOpen={openEvidence} /> : view.query.option === "A" ? <Ledger view={view} onOpen={openEvidence} /> : view.query.option === "B" ? <Editorial view={view} onOpen={openEvidence} /> : <Lens view={view} onOpen={openEvidence} />}
      </div></div>
    </main>
    <p className={styles.statusRegion} role="status" aria-live="polite">{status || taskMessage}</p>
    <dialog ref={dialogRef} className={styles.dialog} aria-labelledby="evidence-title" onCancel={(event) => { event.preventDefault(); closeEvidence(); }}><div className={styles.dialogInner}>{evidence && <><p className={styles.kicker}>Evidence · {evidence.claim.receiptCount} receipts</p><h2 id="evidence-title">{evidence.claim.claim}</h2><p>{evidence.claim.whyItMatters}</p><div className={styles.evidenceContent}>{evidence.receipts.map((receipt) => <article key={receipt.id}><strong>{receipt.kind === "fact" ? "Observed fact" : "Signal inference"} · {receipt.sourceLabel}</strong><p>{receipt.statement}</p>{receipt.detail && <p>{receipt.detail}</p>}<time dateTime={receipt.observedAt ?? undefined}>{receipt.observedAt ? new Date(receipt.observedAt).toLocaleString("en-GB") : "No observation"}</time></article>)}</div><button type="button" className={styles.secondaryAction} onClick={closeEvidence}>Close evidence</button></>}</div></dialog>
    <dialog ref={taskDialogRef} className={styles.confirmDialog} aria-labelledby="task-title" onCancel={(event) => { event.preventDefault(); closeTask(); }}><div className={styles.dialogInner}>{taskClaim && <><p className={styles.kicker}>Simulated handoff</p><h2 id="task-title">Create a Task from this signal?</h2><p>{taskClaim.nextAction}</p><p className={styles.claimMeta}>Destination · {view.scope.label}<br />No production data will be written.</p>{taskMessage && <p role="status">{taskMessage}</p>}<div className={styles.actionRow}><button type="button" className={styles.secondaryAction} onClick={closeTask}>Cancel</button><button type="button" className={styles.primaryAction} onClick={submitTask} disabled={Boolean(taskMessage)}>Confirm handoff</button></div></>}</div></dialog>
  </div>;
}

function Loading() { return <div className={styles.skeleton} role="status" aria-label="Preparing briefing"><span className={styles.skeletonTitle} /><span className={styles.skeletonLead} /><span className={styles.skeletonLine} /><span className={`${styles.skeletonLine} ${styles.skeletonLineShort}`} /></div>; }
function Lead({ view, claim, onOpen, onTask, compact = false }: { view: SignalLabView; claim: SignalLabClaim; onOpen: (claim: SignalLabClaim, button: HTMLButtonElement) => void; onTask?: (claim: SignalLabClaim, button: HTMLButtonElement) => void; compact?: boolean }) { return <article className={compact ? styles.claimItem : styles.editorialLead}><p className={styles.kicker}>{claim.block === "needs-attention" ? "Needs attention" : claim.block === "moving-well" ? "Moving well" : "Quiet risk"}</p>{compact ? <p className={styles.claimText}>{claim.claim}</p> : <h1 className={styles.leadTitle}>{claim.claim}</h1>}<p className={compact ? undefined : styles.leadBody}>{claim.whyItMatters}</p><p className={styles.leadAction}>Next: {claim.nextAction}</p><div className={styles.claimControls}><button type="button" className={styles.secondaryAction} aria-label={`Open evidence for ${claim.claim}`} onClick={(e) => onOpen(claim, e.currentTarget)}>Evidence <span aria-hidden="true">({claim.receiptCount})</span></button>{onTask && <button type="button" className={styles.quietAction} disabled={!view.canCreateTask} onClick={(e) => onTask(claim, e.currentTarget)}>Create Task</button>}</div></article>; }
function Empty({ view }: { view: SignalLabView }) { return <div className={styles.modeNotice}><h1>{view.headline}</h1><p>{view.summary}</p></div>; }
function TodaySurface({ view, onOpen }: any) { const lead = view.claims[0]; return <article className={styles.todaySurface}><header className={styles.editorialHeader}><p className={styles.kicker}>Today Signal · {view.scope.label}</p><p className={styles.editorialDeck}>The smallest useful read for this morning.</p></header>{lead ? <Lead view={view} claim={lead} onOpen={onOpen} /> : <Empty view={view} />}</article>; }
function Ledger({ view, onOpen, onTask }: any) { const lead = view.claims[0]; return <article className={styles.ledger}><header className={styles.ledgerHeader}><p className={styles.kicker}>Briefing ledger</p><h1>{lead ? "The one thing to move today" : view.headline}</h1><p>{view.summary}</p></header>{lead ? <div className={styles.ledgerGrid}><div className={styles.ledgerMain}><Lead view={view} claim={lead} onOpen={onOpen} onTask={onTask} /><section className={styles.ledgerSection}><h2 className={styles.sectionTitle}>Supporting signals</h2><ul className={styles.claimList}>{view.claims.slice(1).map((claim: SignalLabClaim) => <li key={claim.id}><Lead view={view} claim={claim} compact onOpen={onOpen} onTask={onTask} /></li>)}</ul></section></div><aside className={styles.ledgerRail} aria-label="Ledger context"><div className={styles.railGroup}><h2>Read</h2><p>One lead, {view.claims.length - 1} supporting signal{view.claims.length - 1 === 1 ? "" : "s"}.</p></div><div className={styles.railGroup}><h2>Coverage</h2><p>{view.coverageStatement}</p></div></aside></div> : <Empty view={view} />}</article>; }
function Editorial({ view, onOpen, onTask }: any) { const lead = view.claims[0]; return <article className={styles.editorial}><header className={styles.editorialHeader}><p className={styles.kicker}>Today Signal · {view.scope.label}</p><p className={styles.editorialDeck}>{view.summary}</p></header>{lead ? <><Lead view={view} claim={lead} onOpen={onOpen} onTask={onTask} /><section className={styles.editorialSection}><h2 className={styles.sectionTitle}>The rest of the read</h2><div className={styles.editorialClaims}>{view.claims.slice(1).map((claim: SignalLabClaim, index: number) => <article className={styles.editorialClaim} key={claim.id}><span className={styles.footnoteIndex}>{index + 2}</span><Lead view={view} claim={claim} compact onOpen={onOpen} onTask={onTask} /></article>)}</div></section></> : <Empty view={view} />}</article>; }
function Lens({ view, onOpen, onTask }: any) { const [selected, setSelected] = useState(view.claims[0]); return <article className={styles.lens}><header className={styles.lensHeader}><p className={styles.kicker}>Signal Lens</p><h1>{selected ? selected.claim : view.headline}</h1><p>{view.summary}</p></header>{selected ? <div className={styles.lensGrid}><div className={styles.lensBrief}><Lead view={view} claim={selected} onOpen={onOpen} onTask={onTask} /><h2 className={styles.sectionTitle}>Other signals</h2><ul className={styles.claimList}>{view.claims.filter((claim: SignalLabClaim) => claim.id !== selected.id).map((claim: SignalLabClaim) => <li key={claim.id}><button type="button" className={styles.claimItem} aria-current={selected.id === claim.id ? "true" : undefined} onClick={() => setSelected(claim)}><span className={styles.kicker}>{claim.block}</span><span className={styles.claimText}>{claim.claim}</span></button></li>)}</ul></div><aside className={styles.lensProof} aria-labelledby="lens-proof-title"><h2 id="lens-proof-title">Proof for this signal</h2><p>{selected.receiptCount} receipts · {selected.freshness} source</p><button type="button" className={styles.secondaryAction} onClick={(e) => onOpen(selected, e.currentTarget)}>Open evidence</button></aside></div> : <Empty view={view} />}</article>; }
function EvidenceSurface({ view, onOpen }: any) { const claim = view.claims[0]; return <article className={styles.editorial}><header className={styles.editorialHeader}><p className={styles.kicker}>Evidence index</p><h1>{claim ? "Proof stays close to the claim" : view.headline}</h1><p>{view.summary}</p></header>{claim ? <ul className={styles.claimList}>{view.claims.map((item: SignalLabClaim) => <li key={item.id}><Lead view={view} claim={item} compact onOpen={onOpen} /></li>)}</ul> : <Empty view={view} />}</article>; }
function History({ view }: { view: SignalLabView }) { return <article className={styles.history}><header className={styles.historyHeader}><p className={styles.kicker}>Scope + history</p><h1>{view.scope.label}</h1><p>Fixture editions remain readable without pretending to be persisted product history.</p></header><section><h2 className={styles.sectionTitle}>Previous editions</h2><ol className={styles.historyList}>{view.history.map((edition) => <li className={styles.historyEdition} key={edition.id}><time dateTime={edition.publishedAt}>{new Date(edition.publishedAt).toLocaleDateString("en-GB", { dateStyle: "full" })}</time><h3>{edition.title}</h3><p>{edition.summary}</p></li>)}</ol></section><div className={styles.feedback}><p>Was this briefing useful?</p><div className={styles.feedbackControls}><button type="button" className={styles.secondaryAction}>Yes</button><button type="button" className={styles.quietAction}>Not really</button></div></div></article>; }
